### ISSUE TITLE
Dockerfile seems to be outdated

### ISSUE THREAD

**Issue by Plucks77** [LakhindarPal/discord-player-bot#151]
**Describe the bug**
When building and running the current Dockerfile, it complains about two things: 

First: "Error: Could not load youtube library. Install one of "youtube-ext", "ytdl-core", "@distube/ytdl-core", "play-dl", "yt-stream"
Which is not that problematic, since running locally it also throws this error, but the bot works fine.
EDIT: I also changed `npm` to `yarn` by removing `package-lock.json` and running `yarn install`. With `npm` this seems to be a problem for some reason.

Then when trying to play a song, it throws the second:
"Error: Could not load opus module, tried 5 different modules. Errors: Failed to load mediaplex: Error: Cannot find module 'mediaplex-linux-arm64-gnu'"
This one is the problematic, since it just not play the song.

**To Reproduce**

1. Clone the repo with: `git clone git@github.com:LakhindarPal/discord-player-bot.git` and cd into it
2. Fill `.env` with `DISCORD_TOKEN`, `CLIENT_ID`, `DEV_GUILD`, `NODE_ENV`
3. Build the image with `docker build -t discord-bot .`
4. Run a container with the image with `docker run --env-file .env discord-bot`

**Expected behavior**
The bot should run and be able to play songs

**Screenshots**
<img width="1207" alt="Screenshot 2024-08-04 at 14 47 21" src="https://github.com/user-attachments/assets/ddf3430c-f5eb-41ec-bead-809906aa3bdf">
<img width="1212" alt="Screenshot 2024-08-04 at 14 47 43" src="https://github.com/user-attachments/assets/ff333aad-8195-4b50-917d-ab88810f9402">

**Additional Information:**

No additional information needed, since I'm trying to run the Dockerfile, locally it works fine, even though it throws the first described error

**Additional context**
No additional context needed

**Comment by LakhindarPal** [comment]
1. This issue is a bug. The extractor was not registered correctly. Since we are using `discors-player-youtubei` plugin, there's no need to install dependencies like `ytdl-core`, `youtube-ext` etc. But we have to exclude the default youtube extractor from being registered. 
The following change should solve the issue.
https://github.com/LakhindarPal/discord-player-bot/blob/633ce0e7a440bbd696f47c49de9189a597e916f1/src/index.js#L30
```diff
- await player.extractors.loadDefault();
+ await player.extractors.loadDefault((ext) => !['YouTubeExtractor'].includes(ext));
```

2. I believe the docker file is fine, as I'd just pushed a new version to dockerhub and didn't get such error. But the problem could be due to opus library not being compatible. We are using `mediaplex` as opus library, which requires some dependencies of its own depending on the machine you are using. You can try using a different opus library from the below list
```bash
$ npm install --save mediaplex
# or
$ npm install --save @discordjs/opus
# or
$ npm install --save opusscript
# or
$ npm install --save @evan/opus
# or
$ npm install --save node-opus
```

**Comment by LakhindarPal** [comment]
The latest commit (fbb104e88e2440404cfff2b610713a1df2e33c6f) should fix this issue.
And if you want to use docker, I highly suggest you to pull the hosted version from [Dockerhub](https://hub.docker.com/r/lakhindarpal/discord-player-bot) since it is tested.
